version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10.2"
    steps:
      - checkout
      - name: install dependencies
          command:
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: python3 main.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build