version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10.2-browsers"
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - run: python3 main.py
workflows:
  build_and_test:
    jobs:
      - build
